version: '3.8'

services:
  db:
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: todos
      # MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
    image: mysql
    ports:
      - 3306:3306
    restart: always
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
    driver: local
